CREATE TABLE github_profiles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255),
    followers INT DEFAULT 0,
    following INT DEFAULT 0,
    public_repos INT DEFAULT 0,
    bio TEXT,
    location VARCHAR(255),
    company VARCHAR(255),
    blog VARCHAR(255),
    twitter_username VARCHAR(255),
    public_gists INT DEFAULT 0,
    avatar_url TEXT,
    created_at_github DATETIME,
    account_age_days INT DEFAULT 0,
    top_language VARCHAR(100),
    total_stars INT DEFAULT 0,
    total_forks INT DEFAULT 0,
    most_starred_repo VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);